FROM openjdk:11-windowsservercore-ltsc2022

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN New-Item -ItemType Directory -Force -Path C:\opt

COPY scripts/download_detect.ps1 C:/opt/

RUN C:/opt/download_detect.ps1

COPY release/windows/amd64/blackduck-plugin.exe C:/bin/

ENTRYPOINT ["C:/bin/blackduck-plugin.exe"]